In [1]:
#data manipulation
import pandas as pd

#xisualization
import matplotlib.pyplot as plt

# for preprocessing text
import re
from spacy.lang.en.stop_words import STOP_WORDS

from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')
"""
The Python statement import warnings; warnings.filterwarnings('ignore') serves to suppress or hide all warning 
messages that might otherwise be displayed during the execution of a Python program
"""

"\nThe Python statement import warnings; warnings.filterwarnings('ignore') serves to suppress or hide all warning \nmessages that might otherwise be displayed during the execution of a Python program\n"

In [2]:
df=pd.read_csv(r"D:\Datasets\complaint priority\cleaned_data.csv")

In [3]:
df.head(5)

            Product                                 Consumer Complaint
0  Credit reporting  I have outdated information on my credit repor...
1     Consumer Loan  I purchased a new car on XXXX XXXX. The car de...
2  Credit reporting  An account on my credit report has a mistaken ...
3   Debt collection  This company refuses to provide me verificatio...
4   Debt collection  This complaint is in regards to Square Two Fin...

In [4]:
# no: of rows in the dataset

df.shape[0]

2029

In [5]:
# the no:of rows in every classes in the target column

df['Product'].value_counts()

Product
Debt collection            519
Mortgage                   407
Credit reporting           395
Credit card                270
Bank account or service    185
Student loan               145
Consumer Loan              108
Name: count, dtype: int64

## Text preprocessing

Randomly looking at compliaints of every classes of the column product , and finding any weird/strange words that need to be pruned for the model building wich can affect the model's performance

In [10]:
# Randomly sampling(n=1) in Debt collection class to chech the text and words in it

# Debt collection

print(df[df['Product'] == 'Debt collection']['Consumer Complaint'].sample(n=1).iloc[0])

Please see Complaint # XXXX ( I have recopied it below ). It is the very same details except they are now using a different number to call from. Now they have called XXXX ( Re-copying complaint filed XXXX/XXXX/2016 as now they are using a different number ) For the last 2 months I have been receiving calls from multiple local numbers with a XXXX or XXXX area code. When I answer the calls just drop. I call the number back, and I hear music for a few seconds and someone Answers. The person comes on trying to obtain personal information from me. On XXXX XXXX, 2016, I received a call around XXXX. EST again from XXXX and the same thing happend. I answered and then the call dropped. I called back from a different number and the representative indicated they were with Halstead Financial and that they would need more information. I have not received any correspondence from this company. The representative indicated they could not provide any information to me without verification, she asked what number was receiving the calls. Although reluctant, I decided to confirm my phone number with her, because the calls are frequent and disruptive. Additionally the fact that all the calls result in hang up on their end as soon as I answer. For the last few weeks I have been monitoring my calls more and that 's when I noticed the similar number. Once I confirmed the number she was calling she asked for my social security number which refused to provide. I asked to have a letter detailing the issue sent to me and was told " how can we send a letter if we ca n't verify who you are '' I told the representative I would not provide information and I would like my name removed from their call list. I was told that was not going to happen and that I would be receiving more calls. I have no idea what this company does or what they are claiming with respect to me. I am concerned because in XXXX of this year I was a victim of identity theft. Since that time, I have been receiving numerous calls from unknown and strange numbers, my mail was also intercepted on 2 occasions for weeks at a time, and my financial information was delivered to other addresses. I also checked and I do not see that this company is licensed as a collection agency in my state.
Consent to publish the description of what happened

In [7]:
# Randomly sampling(n=1) in Mortgage class to chech the text and words in it

# Mortgage

print(df[df['Product'] == 'Mortgage']['Consumer Complaint'].sample(n=1).iloc[0])

i filed a complaint 2 years ago.
To : XXXXXXXXXXXX : RE : Y XXXX submission [ Case number : XXXX ] Date : Wed, XXXX XXXX 2013 XXXX XXXX, They ( wellsfargo and assurant ) dodged issues, by ignoring my requests and answering an answer that does not pretain to a quastion, also send in tons of irrelevant paperwork, just to drind CFPB down, it is part of their tactics.
Now it became absolutely clear, what XXXX is doing is beyond writing a worthless check, whcih is withour a doubt criminal offense. I want you to reopen my case, review and compare forclosure procedure in XXXX court, XXXX civil law. Also i have reported him and XXXX XXXX ( XXXX CEO ) to the feds and FBI in XXXX result.

Reason for refusal to pay is force placed insurance product. Also refusal to review odifications XXXX attempts already, currently the XXXX is in progress @ wells Fargo.

In [41]:
# Randomly sampling(n=1) in Credit reporting class to chech the text and words in it

# Credit reporting

print(df[df['Product'] == 'Credit reporting']['Consumer Complaint'].sample(n=1).iloc[0])

I attempted to receive my free copy of my Equifax credit report via XXXX. I was prompted to submit additional information via regular mail in order to receive the report. I called the number to speak with a live agent ( XXXX ) XXXX. Once I got a live representative she was unable to provide me with my report as well even though I provided her with all of my identification information. I would like to pay a medical collection that is reporting only with Equifax. I want more information about the clinic/ collection company whom I can pay.

In [44]:
# Randomly sampling(n=1) in Credit card class to chech the text and words in it

# Credit card

print(df[df['Product'] == 'Credit card']['Consumer Complaint'].sample(n=1).iloc[0])

In early XX/XX/2016, I tried logging into my Chase Bank credit card account. I was notified that my email address had been changed, and was asked if it was me. I was not notified of this until I tried to log into my account. I changed the email address back to my actual one and was able to log in. At that time I saw that a Chase Amazon card had been issued in my name, that I never requested. I also saw that there were 4 fraudulent charges on my Chase Sapphire credit card, all small charges to Amazon digital services. I spoke to Chase 's fraud department -- they took off the charges, and closed the fraudulent Chase Amazon credit card. I put a 90 day fraud alert on my credit report. However, I just learned last night, after deciding to reinitiate the 90 day fraud alert for my safety, that there have been TWO more hard inquiries on my credit report, all from Chase Bank. One in XX/XX/2016, and one in XX/XX/2016. How did this happen, if I have a fraud alert on my credit reports? I was never notified by Chase, I was never called by anyone. And yet, two more hard credit inquires from Chase Bank on my credit report, thereby negatively affecting my credit score. I called Chase Bank, spoke yet again to the fraud department. I found out that the two latest inquiries were also for Amazon credit cards. Chase did agree to contact the credit bureaus to remove the fraudulent inquiries, but in terms of any protection for me, could NOT explain why this happened in spite of the active 90 day fraud alert with all XXXX credit reporting agencies, NOR could they offer me any additional protection from having new accounts inquiries or cards with Chase. When I asked specifically what other layers of protection Chase could offer, such as freezing my account so that no more inquiries would be allowed, or needing additional information from a person if they try to apply for an account ... they offered nothing. Just reading from written materials to me, the same thing I 've heard before about putting a fraud alert on my account. Which has not helped me AT ALL with Chase. Considering someone got into my Chase account and changed the email address, and I 'm not being notified when new inquiries are happening, in spite of a fraud alert being on my credit reports ... this certainly seems like an inside job, with Chase and perhaps with Amazon. When I asked to speak to a manager, someone higher up, I was denied that request.

In [49]:
# Randomly sampling(n=1) in Bank account or service class to chech the text and words in it

# Bank account or service

print(df[df['Product'] == 'Bank account or service']['Consumer Complaint'].sample(n=1).iloc[0])

Wells Fargo deposited and cashed a XXXX party check without having the required XXXX signatures. Outcome to XXXX XXXX, 2016 letter from Wells Fargo Original compliant XXXX.
XXXX XXXX, 2016 Subject : original CFPB XXXX XXXX XXXX XXXX since your last correspondence date XXXX XXXX, 2016, I have followed up with XXXX regarding the breach check on XXXX XXXX, 2016. As of XXXX XXXX, 2016 XXXX informed me that Wells Fargo has requested additional documents, I have included Citibank 's correspondence. A S Home Improvement is Wells Fargo client. I have not had any contact with A S Home Improvement since Wells Fargo deposited and cashed the check without the required signature from A S Home Improvement on the XXXX party check. This account and video has been subpoena by XXXX. Contact XXXX XXXX XXXX regarding the police report and warrant.
Although you have stated Wells Fargo corresponds directly with XXXX, XXXX suggest that I correspond with Wells Fargo. It appears to become a XXXX game that I can not entertain. Wells Fargo gave the funds away without following Banking Regulations. I am the victim of this crime. The request for me to get an affidavit from your client, who has vanished, is absurd. Wells Fargo is liable because banking protocol was not followed. Therefore, the breach check needs to be replaced in full and sent to XXXX. More than enough time has passed to resolve this issue.

CC : CFPB

In [48]:
# Randomly sampling(n=1) in Student loan class to chech the text and words in it

# Student loan

print(df[df['Product'] == 'Student loan']['Consumer Complaint'].sample(n=1).iloc[0])

On XX/XX/XXXX I was hit by a car and sustained XXXX XXXX and had XXXX done. I have been unable to work. I provided documentation to Navient and qualified for the income-contigent plan on the federal loans. For the private loans I was told I used my all my forbearance time but my recollection is that I did NOT use it all. I had no way to contest this and was offered no other option but to pay for the private loans in spite of my explaining my situation. I have no sick pay while I am out and not working. When they call me, it 's several times a day and sometimes a voice message telling me to call them so I can speak to a specialist that will offer me options. However I am NEVER offered options and instead told I must pay, in spite of my situation. I feel harassed by these calls as they will take place several times in one day, and in some cases the people have been rude. One occasion they asked me how am I able to pay other bills and this is really none of their business how I am managing. I was then told 'okay so you refuse to answer '. Their wording of my questions is that I am solely to blame. Furthermore, I have been paying off these loans diligently and have obeyed all their rules since I took these loans out in XX/XX/XXXX. Repayment began in XX/XX/XXXX and I have been paying regularly since then with more than % 8 interest. I am trapped in this interest rate and it is extremely difficult for me. I have been offered no other options and I do no know what to do.

In [11]:
# Randomly sampling(n=1) in Consumer Loan class to chech the text and words in it

# Consumer Loan

print(df[df['Product'] == 'Consumer Loan']['Consumer Complaint'].sample(n=1).iloc[0])

I recently took out a HELOC on my house and used part of the loan to payoff my installment loan with Prosper. The payoff was overpaid by {$110.00} to Prosper.com, so I asked Prosper for a refund. Prosper says I still owe them {$130.00} and will not close my account and is continuing to charge me interest. I 'm afraid Prosper is going to charge me late fees and ruin my credit because they wo n't honor the payoff statement they sent me.

I almost lost my rate lock because Prosper would n't provide a payoff statement to the new lender. I had to call repeatedly over a few weeks, and was always promised a statement would follow in 2-3 days from their finance department. It was n't until I filed a complaint with the BBB that I finally received my payoff statement.

Now that I am having issues again with their customer service it has fallen back into the same cycle of them saying they need to send the issue to their finance department and will be in touch in 2-3 days. I filed another complaint with the BBB, but no response this time.

They are ignoring my issue and trying to bully me into submission by holding my money and credit hostage! It is n't right! I 'm on hold for hours with their customer service and having to dig for viable remedies to get them to act.

## Regular Expression

In [12]:
df_pp=df.copy()

In [13]:
df_pp.head()

            Product                                 Consumer Complaint
0  Credit reporting  I have outdated information on my credit repor...
1     Consumer Loan  I purchased a new car on XXXX XXXX. The car de...
2  Credit reporting  An account on my credit report has a mistaken ...
3   Debt collection  This company refuses to provide me verificatio...
4   Debt collection  This complaint is in regards to Square Two Fin...

In [14]:
def regex_normalize(text):
    if not isinstance(text, str):
        return ""
    
    text = text.lower().replace('\n', ' ').replace('\t', ' ') # Lowercase texts and replace /n & /t in the text
    
    text = re.sub(r'\b[0-9/]*X{2,}[0-9/]*\b', '', text) # removes XX/XX/XX19 ,XX/XX/XXXX, XXXX/XXXX/XXXX

    text = re.sub(r'\bx+\b', '', text, flags=re.IGNORECASE) #  replaces xxxx blocks out completely

    text = re.sub(r'\{?\$[0-9.,]+\}?|\{?[0-9.,]+\$\}?', '[MONEY]', text) # replaces any amoount money with currency symbol into token( [MONEY] )
    
    text = re.sub(r'\.{3,}', '', text) # replaces triple dots with nothing in its place

    text = re.sub(r'\d+', '', text) # replaces the numbers like year, two-digit numbers, etc

    text = re.sub(r'[^a-zA-Z\s]', ' ', text) # replaces -(hyphen) before words
    
    text = re.sub(r"\'", "", text) # Removes any backslash that immediately precedes a single quote

    text = re.sub(r'%\s*[0-9.,]+|[0-9.,]+\s*%', '[PERCENTAGE]', text) # replaces the numbers with % with improper placements into token( [PERCENTAGE] )
    
    text = re.sub(r'\s+', ' ', text).strip() # Collapse multiple spaces into a single space

    text = text.replace(r"\'\'", '"').replace(r"\'", "'") # replaces \'' and other slash symbols with single quotaion
    
    return text

In [15]:
df_pp['regexed_complaint'] = df_pp['Consumer Complaint'].apply(regex_normalize)

In [16]:
df_pp.head()

,Product,Consumer Complaint,regexed_complaint
0,Credit reporting,I have outdated information on my credit repor...,i have outdated information on my credit repor...
1,Consumer Loan,I purchased a new car on XXXX XXXX. The car de...,i purchased a new car on the car dealer called...
2,Credit reporting,An account on my credit report has a mistaken ...,an account on my credit report has a mistaken ...
3,Debt collection,This company refuses to provide me verificatio...,this company refuses to provide me verificatio...
4,Debt collection,This complaint is in regards to Square Two Fin...,this complaint is in regards to square two fin...

In [17]:
df_pp['regexed_complaint'][2]

'an account on my credit report has a mistaken date i mailed in a debt validation letter to allow to correct the information i received a letter in the mail stating that experian received my correspondence and found it to be suspicious and that i did n t write it experian s letter is worded to imply that i am incapable of writing my own letter i was deeply offended by this implication i called experian to figure out why my letter was so suspicious i spoke to a representative who was incredibly unhelpful she did not effectively answer any questions i asked of her and she kept ignoring what i was saying regarding the offensive letter and my dispute process i feel the representative did what she wanted to do and i am not satisfied it is still not clear to me why i received this letter i typed this letter i signed this letter and i paid to mail this letter yet experian willfully disregarded my lawful request i am disgusted with this entire situation and i would like for my dispute to be handled appropriately and i would like for an experian representative to contact me and give me a real explanation for this letter'

In [18]:
df_pp['regexed_complaint'][1]

'i purchased a new car on the car dealer called citizens bank to get a day payoff on my loan good till the dealer sent the check the next day when i balanced my checkbook on i noticed that citizens bank had taken the automatic payment out of my checking account at bank i called citizens and they stated that they did not close the loan until stating that they did not receive the check until i told them that i did not believe that the check took that long to arrive told me a check was issued to me for the amount overpaid they deducted additional interest today i called citizens bank again and talked to a supervisor named because on i received a letter that the loan had been paid in full dated but no refund check was included stated that they hold any over payment for business days after the loan was satisfied and that my check would be mailed out on wed the i questioned her about the delay in posting the dealer payment and she first stated that sometimes it takes or business days to post then she said they did not receive the check till i again told her that i did not believe this and asked where is my money she then stated that they hold the over payment for business days i asked her why and she simply said that is their policy i asked her if i would receive interest on my money and she stated no i believe that citizens bank is deliberately delaying the posting of payment and the return of consumer s money to make additional interest for the bank if this is not illegal it should be it does hurt the consumer and is not ethical my amount of money lost is minimal but if they are doing this on thousands of car loans a month then the additional interest earned for them could be staggering i still have another car loan from citizens bank and i am afraid when i trade that car in another year i will run into the same problem again'

In [20]:
print(df_pp[df_pp['Product'] == 'Consumer Loan']['regexed_complaint'].sample(n=1).iloc[0])

mercedes benz financial services mbfs has refused to refund an overpayment to my account in the amount of MONEY the payment was made while i was in the process of transferring my lease along with the paperwork for the lease transfer mbfs required what would be my final payment due on and so i sent them a check which mbfs cashed while the lease transfer paperwork was being processed and as the due date approached mbfs left multiple messages on my phone asking that i send in my payment not wishing to derail the lease transfer at the expense of the transferee i logged into my mbfs account and made an electronic payment of MONEY thus i made payments for and figured that mbfs would refund the overpayment and indeed its representative said i had a refund due when i called to check the status of my refund i was troubled during that call because it took mbfs an inordinate amount of time to locate my account when arrived and no refund had arrived i called mbfs again and it took them at least half an hour to find my records as it appears that my account has been virtually deleted from their system that phone call lasted well over minutes and i was placed on hold during much of it mbfs eventually informed me that because the account is no longer in my name any money that is due to me must be paid to me by the person who took over my lease that is not correct because the overpayment was made while the account was still in my name and therefore it is mbfs that improperly kept my money and must refund it the lease transfer was complete as of and my check was presented on with the electronic payment having been made on proof of these payments will be attached in any event the transferee of my lease is an innocent bystander and should not be troubled by any of this

## Lemmatization

In [22]:
import spacy

nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])

def lemmatize_row(text):
    if not isinstance(text, str) or not text.strip():
        return ""
    
    doc = nlp(text)
    
    # Extract the lemma only if it is NOT punctuation, a symbol, or a standalone period
    lemmas = [token.lemma_ for token in doc if not token.is_punct and token.pos_ != "SYM" and token.lemma_ != "."]
    
    return " ".join(lemmas)

In [23]:
df_pp['lemmatized_complaint'] = [lemmatize_row(text) for text in df_pp['regexed_complaint']]

In [28]:
df_pp.head(5)

,Product,Consumer Complaint,regexed_complaint,lemmatized_complaint
0,Credit reporting,I have outdated information on my credit repor...,i have outdated information on my credit repor...,I have outdate information on my credit report...
1,Consumer Loan,I purchased a new car on XXXX XXXX. The car de...,i purchased a new car on the car dealer called...,I purchase a new car on the car dealer call ci...
2,Credit reporting,An account on my credit report has a mistaken ...,an account on my credit report has a mistaken ...,an account on my credit report have a mistaken...
3,Debt collection,This company refuses to provide me verificatio...,this company refuses to provide me verificatio...,this company refuse to provide I verification ...
4,Debt collection,This complaint is in regards to Square Two Fin...,this complaint is in regards to square two fin...,this complaint be in regard to square two fina...

In [67]:
df_pp['lemmatized_complaint'][1]

'I purchase a new car on the car dealer call citizen bank to get a day payoff on my loan good till the dealer send the check the next day when I balance my checkbook on I notice that citizen bank have take the automatic payment out of my checking account at bank I call citizen and they state that they do not close the loan until state that they do not receive the check until I tell they that I do not believe that the check take that long to arrive tell I a check be issue to I for the amount overpay they deduct additional interest today I call citizen bank again and talk to a supervisor name because on I receive a letter that the loan have be pay in full date but no refund check be include state that they hold any over payment for business day after the loan be satisfied and that my check would be mail out on we d the I question she about the delay in post the dealer payment and she first state that sometimes it take or business day to post then she say they do not receive the check till I again tell she that I do not believe this and ask where be my money she then state that they hold the over payment for business day I ask she why and she simply say that be their policy I ask she if I would receive interest on my money and she state no I believe that citizen bank be deliberately delay the posting of payment and the return of consumer s money to make additional interest for the bank if this be not illegal it should be it do hurt the consumer and be not ethical my amount of money lose be minimal but if they be do this on thousand of car loan a month then the additional interest earn for they could be staggering I still have another car loan from citizen bank and I be afraid when I trade that car in another year I will run into the same problem again'

In [42]:
df_pp['lemmatized_complaint'][49]

'previous case numbersince my last write complaint nationstar approve a hamp but not what be originally agree to do not take off my ex husband or give I the interest rate offer by aurora bank my payment go up with this version of the hamp but I be tell my ex husband who be on the loan would be remove with this new hamp so in order to get my ex husband off the loan I agree and sign the hamp when I receive the hamp paperwork I be shock and dismay my ex husband be still on the paperwork and I get a high interest rate upon call my rep he explain that he would attach my divorce decree and quit claim deed where the property be quit claim to I solely by my ex husband that this would remove his name from the loan so I sign and return the paperwork regardless of the high rate to attain this end I attach the email from the nationstar rep state that his name would be remove I sign the paperwork with my ex husband name on it without his signature nationstar sign and record this document see attach my ex husband serve I with a lawsuit for not make payment ruin his credit and for not take he off the loan when I call nationstar about this the say they will not remove his name off the loan even with the paperwork I sign the proof I send and the write email from their company now I come to find out that they fraudulently manipulate my credit report to show late payment that never occur put my payment in a suspense account all of my payment have be on time and I have copy of the cancel check to prove it so they admit their manipulation of the credit report however it also affect my ex husband credit report their fraudulent action not only affect I but my ex husband as well from which I understand this be a federal offense I be now in the year of this process I accept aurora offer at PERCENTAGE and take my ex husband name off the loan upon the sale of this loan to nationstar they claim they lose the paperwork funny how they say they lose it but yet they accept modify payment they say they lose so I have to start the process all over again I have now have to hire attorney to try and straighten out this mess one to defend my husband lawsuit and the other to make nationstar do what the say in writing we be still go back and forth with nationstar to do what they say if you would like to verify that last sentence you may contact my ex father in law which I can supply his name and number if request'

In [25]:
df_pp['Product'][49]

'Mortgage'

## Stopwords removal

In [27]:
from spacy.lang.en.stop_words import STOP_WORDS


stopwords = set(STOP_WORDS)

custom_stopwords = {"complaint", "case", "number", "regards", "listed", 
                    "attached", "document", "pdf", "company", "bank", 
                    "loan", "citizen", "account","receive", "say", 
                    "tell", "call", "state", "go", "would", "could",
                    "citibank", "citcard", "recieve", "fradulent", 
                    "website", "show", "tell", "say", "talk", "ask",
                    "tell", "say","talk", "advise", "receive", "state", 
                    "include", "question", "website", "show", "transferee",
                    "husband", "father", "law", "attorney", "rep", "supervisor", 
                    "name","numbersince", "forth", "till", "today", 
                    "yesterday", "tomorrow","sentence", "contact", "supply", 
                    "request", "letter", "email", "writing"
                   }

final_stopwords = stopwords.union(custom_stopwords) # Combine them into a single high-speed lookup set


def filter_tokens(text): # FILTER FUNC
    if not isinstance(text, str) or not text.strip():
        return ""
    
    words = text.split()
 
    filtered_words = [word for word in words if word not in final_stopwords and len(word) > 2]
    
    return " ".join(filtered_words)

In [29]:
df_pp['stopwords_cleaned_complaint'] = df_pp['lemmatized_complaint'].apply(filter_tokens)

In [37]:
df_pp.head(5)

,Product,Consumer Complaint,regexed_complaint,lemmatized_complaint,stopwords_cleaned_complaint
0,Credit reporting,I have outdated information on my credit repor...,i have outdated information on my credit repor...,I have outdate information on my credit report...,outdate information credit report previously d...
1,Consumer Loan,I purchased a new car on XXXX XXXX. The car de...,i purchased a new car on the car dealer called...,I purchase a new car on the car dealer call ci...,purchase new car car dealer day payoff good de...
2,Credit reporting,An account on my credit report has a mistaken ...,an account on my credit report has a mistaken ...,an account on my credit report have a mistaken...,credit report mistaken date mail debt validati...
3,Debt collection,This company refuses to provide me verificatio...,this company refuses to provide me verificatio...,this company refuse to provide I verification ...,refuse provide verification validation debt ri...
4,Debt collection,This complaint is in regards to Square Two Fin...,this complaint is in regards to square two fin...,this complaint be in regard to square two fina...,regard square financial refer cfpb regard cach...

In [38]:
df_pp['stopwords_cleaned_complaint'][49]

'previous write nationstar approve hamp originally agree interest rate offer aurora payment version hamp remove new hamp order agree sign hamp hamp paperwork shock dismay paperwork high interest rate explain attach divorce decree quit claim deed property quit claim solely remove sign return paperwork regardless high rate attain end attach nationstar remove sign paperwork signature nationstar sign record attach serve lawsuit payment ruin credit nationstar remove paperwork sign proof send write come find fraudulently manipulate credit report late payment occur payment suspense payment time copy cancel check prove admit manipulation credit report affect credit report fraudulent action affect understand federal offense year process accept aurora offer sale nationstar claim lose paperwork funny lose accept modify payment lose start process hire try straighten mess defend lawsuit nationstar write nationstar like verify'

In [39]:
df_pp['stopwords_cleaned_complaint'][1]

'purchase new car car dealer day payoff good dealer send check day balance checkbook notice automatic payment checking close check believe check long arrive check issue overpay deduct additional interest pay date refund check hold payment business day satisfied check mail delay post dealer payment business day post check believe money hold payment business day simply policy interest money believe deliberately delay posting payment return consumer money additional interest illegal hurt consumer ethical money lose minimal thousand car month additional interest earn staggering car afraid trade car year run problem'

In [42]:
#print(df_pp[df_pp['product']== 'Consumer Loan']['Consumer Complaint'].sample(n=1).iloc[0])


print(df_pp[df_pp['Product'] == 'Consumer Loan']['stopwords_cleaned_complaint'].sample(n=1).iloc[0])

spouse new carpet installer come sitter instal wrong carpet notify correct installer come day later remove carpet plywood floor child buy unable job issue installer complete pay point finger carpet purchase new credit card cash month cancel order month frustration carpet instal week time holiday refund entire order cancel card month later invoice midland funding pay local manager corporate office resolve fast forward hear sue order money hearing magistrate creditor issue dismiss later year hospital believe time file judgment notification judgement file fair practice upset collect joint cost thousand remove fair cheat badly happen county court house money judgement sheriff levy property need correct victim unfair business practice accord balance credit

In [44]:
df_pp.head(3)

,Product,Consumer Complaint,regexed_complaint,lemmatized_complaint,stopwords_cleaned_complaint
0,Credit reporting,I have outdated information on my credit repor...,i have outdated information on my credit repor...,I have outdate information on my credit report...,outdate information credit report previously d...
1,Consumer Loan,I purchased a new car on XXXX XXXX. The car de...,i purchased a new car on the car dealer called...,I purchase a new car on the car dealer call ci...,purchase new car car dealer day payoff good de...
2,Credit reporting,An account on my credit report has a mistaken ...,an account on my credit report has a mistaken ...,an account on my credit report have a mistaken...,credit report mistaken date mail debt validati...

In [45]:
# taking only the required columns for the NLP application

preprocessed=df_pp.iloc[:,[4,0]].reset_index(drop=True)

In [46]:
preprocessed.head(3)

                         stopwords_cleaned_complaint           Product
0  outdate information credit report previously d...  Credit reporting
1  purchase new car car dealer day payoff good de...     Consumer Loan
2  credit report mistaken date mail debt validati...  Credit reporting

In [48]:
# Save the DataFrame to a CSV file

preprocessed.to_csv('D:\Datasets\complaint priority\preprocessed_complaints.csv', index=False)